# 자료형(Data Type)

## Bool(True, False)

In [2]:
type(True)

bool

In [3]:
type(False)

bool

## int(1,2,3 ...), Float(1.1, 1.12, 1.123, ...), complex(1+3j, 2+4j, ...)

In [4]:
type(1)

int

In [5]:
type(1.234)

float

In [6]:
type(1+2j)

complex

## String(a, b, c, ...), list, tuple, dict, fuction

In [7]:
type('a')

str

In [8]:
type("a")

str

In [9]:
type([1,2,3])

list

In [10]:
type([[1,2,3], [4,5,6]])

list

In [11]:
type((1,2,3))

tuple

In [12]:
type({'a': 1, 'b': 2, 'c': 3})

dict

# 파이썬 타입 변환, 형변환 (float, int, str, chr, bool)

# https://blockdmask.tistory.com/432 참조

# int: 정수형

In [1]:
# int(정수) : 정수를 정수로 변환 (가능함. 의미없음)
a = int(10)
print(f'1. int(10) = {a}, type(a) = {type(a)}')

1. int(10) = 10, type(a) = <class 'int'>


In [2]:
# int(실수) : 실수를 정수로 변환
b = int(3.141592)
print(f'2. int(3.141592) = {b}, type(b) = {type(b)}')

2. int(3.141592) = 3, type(b) = <class 'int'>


In [3]:
# int(불리언) : 불리언을 정수로 변환
c = int(True)
print(f'3. int(True) = {c}, type(c) = {type(c)}')

3. int(True) = 1, type(c) = <class 'int'>


In [4]:
# int(문자) : 문자를 정수로 변환
# d = int('a') 오류 변환할 정수가 없음
d = int('1')
print(f'4. int("1") = {d}, type(d) = {type(d)}')

4. int("1") = 1, type(d) = <class 'int'>


In [5]:
# int(문자열) : 문자열을 정수로 변환
# e = int('blockdmask') 오류 변환할 정수가 없음
e = int('112')
print(f'5. int(\'112\') = {e}, type(e) = {type(e)}')

5. int('112') = 112, type(e) = <class 'int'>


# float: 실수형

In [6]:
# float(정수) : 정수를 실수로 변환
a = float(10)
print(f'1. float(10) = {a}, type(a) = {type(a)}')

1. float(10) = 10.0, type(a) = <class 'float'>


In [7]:
# float(실수) : 실수를 실수로 변환 (가능, 의미없음)
b = float(3.141592)
print(f'2. float(3.141592) = {b}, type(b) = {type(b)}')

2. float(3.141592) = 3.141592, type(b) = <class 'float'>


In [8]:
# float(불리언) : 불리언을 실수로 변환
c = float(False)
print(f'3. float(False) = {c}, type(c) = {type(c)}')

3. float(False) = 0.0, type(c) = <class 'float'>


In [9]:
# float(문자) : 문자를 실수로 변환
# d = float('a')  # 오류 : 변환할 실수가 없음
d = float('2')
print(f'4. float("2") = {d}, type(d) = {type(d)}')

4. float("2") = 2.0, type(d) = <class 'float'>


In [10]:
# float(문자열) : 문자열을 정수로 변환
# e = float('blockdmask') # 오류 : 변환할 실수가 없음
e = float('3434')
print(f'5. float(\'3434\') = {e}, type(e) = {type(e)}')

5. float('3434') = 3434.0, type(e) = <class 'float'>


# str: 문자열

In [11]:
# str(정수) : 정수를 문자열로 변환
a = str(10)
print(f'1. str(10) = {a}, type(a) = {type(a)}')

1. str(10) = 10, type(a) = <class 'str'>


In [12]:
# str(실수) : 실수를 문자열로 변환
b = str(3.141592)
print(f'2. str(3.141592) = {b}, type(b) = {type(b)}')

2. str(3.141592) = 3.141592, type(b) = <class 'str'>


In [13]:
# str(불리언) : 불리언을 문자열로 변환
c1 = str(True)
print(f'3-1. str(True) = {c1}, type(c1) = {type(c1)}')

3-1. str(True) = True, type(c1) = <class 'str'>


In [14]:
c2 = str(False)
print(f'3-2. str(False) = {c2}, type(c2) = {type(c2)}')

3-2. str(False) = False, type(c2) = <class 'str'>


In [15]:
# str(문자) : 문자를 문자열로 변환
d1 = str('2')
print(f'4-1. str("2") = {d1}, type(d1) = {type(d1)}')

4-1. str("2") = 2, type(d1) = <class 'str'>


In [16]:
d2 = str('a')
print(f'4-2. str("a") = {d2}, type(d2) = {type(d2)}')

4-2. str("a") = a, type(d2) = <class 'str'>


In [17]:
# str(문자열) : 문자열을 문자열로 변환 (가능, 의미없음)
e = str('jstrend')
print(f'5. str(\'3434\') = {e}, type(e) = {type(e)}')

5. str('3434') = BlockDMask, type(e) = <class 'str'>


# chr: 문자

In [18]:
# chr(정수) : 정수를 문자로 변환
a = chr(54)
print(f'1. chr(54) = {a}, type(a) = {type(a)}')

1. chr(54) = 6, type(a) = <class 'str'>


In [19]:
b = chr(55)
print(f'2. chr(55) = {b}, type(b) = {type(b)}')

2. chr(55) = 7, type(b) = <class 'str'>


In [20]:
i = 64
while i <= 70:
    print(f'chr({i}) : {chr(i)}')
    i = i + 1

chr(64) : @
chr(65) : A
chr(66) : B
chr(67) : C
chr(68) : D
chr(69) : E
chr(70) : F


In [21]:
# chr(실수) : 실수를 문자로 변환 - 불가능
# b = chr(3.141592)

In [22]:
# chr(불리언) : 불리언을 문자로 변환
# 이 경우에는 True가 1, False가 0으로 취급되어서 가능
c1 = chr(True)
print(f'3-1. chr(True) = {c1}, type(c1) = {type(c1)}')

3-1. chr(True) = , type(c1) = <class 'str'>


In [23]:
c2 = chr(1)
print(f'3-2. chr(1) = {c2}, type(c2) = {type(c2)}')

3-2. chr(1) = , type(c2) = <class 'str'>


In [24]:
if c1 == c2:
    print('c1 == c2')

c1 == c2


In [25]:
c3 = chr(False)
print(f'3-3. chr(False) = {c3}, type(c3) = {type(c3)}')
c4 = chr(0)
print(f'3-4. chr(0) = {c4}, type(c4) = {type(c4)}')

3-3. chr(False) = , type(c3) = <class 'str'>
3-4. chr(0) = , type(c4) = <class 'str'>


In [26]:
if c3 == c4:
    print('c3 == c4')

c3 == c4


In [27]:
# chr(문자) : 문자 입력 - 불가능
# d1 = chr('2')
# d2 = chr('a')
 
# chr(문자열) : 문자열 입력 - 불가능
# e = chr('jstrend')

# bool

In [28]:
# bool(정수) : 정수를 불리언으로 변환
a1 = bool(54)
print(f'1-1. bool(54) = {a1}, type(a1) = {type(a1)}')

1-1. bool(54) = True, type(a1) = <class 'bool'>


In [29]:
a2 = bool(0)
print(f'1-2. bool(0) = {a2}, type(a2) = {type(a2)}')

1-2. bool(0) = False, type(a2) = <class 'bool'>


In [30]:
# bool(실수) : 실수를 불리언으로 변환
b1 = bool(3.141592)
print(f'2-1. bool(3.141592) = {b1}, type(b1) = {type(b1)}')

2-1. bool(3.141592) = True, type(b1) = <class 'bool'>


In [31]:
b2 = bool(0.00)
print(f'2-2. bool(0.00) = {b2}, type(b2) = {type(b2)}')

2-2. bool(0.00) = False, type(b2) = <class 'bool'>


In [32]:
# bool(불리언) : 불리언을 불리언으로 변환
c1 = bool(True)
print(f'3-1. bool(True) = {c1}, type(c1) = {type(c1)}')

3-1. bool(True) = True, type(c1) = <class 'bool'>


In [33]:
c2 = bool(False)
print(f'3-3. bool(False) = {c2}, type(c3) = {type(c2)}')

3-3. bool(False) = False, type(c3) = <class 'bool'>


In [34]:
# bool(문자, 문자열) : 문자열을 불리언으로 변환 (비어있는지 아닌지가 중요)
e = bool('BlockDMask')
print(f'4-1. bool(\'BlockDMask\') = {e}, type(e) = {type(e)}')

4-1. bool('BlockDMask') = True, type(e) = <class 'bool'>


In [35]:
f = bool('')
print(f'4-2. bool(\'\') = {f}, type(f) = {type(f)}')

4-2. bool('') = False, type(f) = <class 'bool'>


# Numpy 배열 형변환

# https://engineer-mole.tistory.com/85

# Numpy의 주요 데이터형 dtype

### int8(i1): 부호 있는 8비트 정수형, int16(i2): 부호 있는 16비트 정수형, int32(i4): 부호 있는 32비트 정수형, int64(i8): 부호 있는 64비트 정수형
### uint8(u1): 부호 없는 8비트 정수형, uint16(u2): 부호 없는 16비트 정수형, uint32(u4): 부호 없는 64비트 정수형, uint64(u8): 부호 없는 64비트 정수형
### float16(f2): 실수형, 반 정밀도 부동소수점형(부호 1비트, 지수 5비트, 가수 10비트), float32(f4): 실수형, 단 정밀도 부동소수점형(부호 1비트, 지수 8비트, 가수 23비트),float64(f4): 실수형, 배 정밀도 부동소수점형(부호 1비트, 지수 11비트, 가수 54비트),float128(f16): 실수형, 4배 정밀도 부동소수점형(부호 1비트, 지수 15비트, 가수 112비트)
###  complex64(c8): 복소수형(실수부,허수부 각각 float32), complex128(c16): 복소수형(실수부,허수부 각각 float64), complex256(c32): 복소수형(실수부,허수부 각각 float128)
### bool(?): 부울형(True or False)
### unicode(U): unicode문자열

In [36]:
import numpy as np
a = np.array([1, 2, 3], dtype=np.int64)
print(a.dtype)
# int64

int64


In [37]:
a = np.array([1, 2, 3], dtype='int64')
print(a.dtype)
# int64

int64


In [38]:
a = np.array([1, 2, 3], dtype='i8')
print(a.dtype)
# int64

int64


# Python형(dtype)

### int(int64), float(float64), str(unicode), 파이선형(unit) => 데이터타입(uni64)

In [39]:
print(int is np.int)

True


<ipython-input-39-7e13aed58217>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(int is np.int)


In [40]:
a = np.array([1, 2, 3], dtype=int)
print(a.dtype)

int32


In [41]:
a = np.array([1, 2, 3], dtype='int')
print(a.dtype)

int32


# 숫자형이 취할 수 있는 범위 (최소값, 최대값)의 확인

## np.iinfo()

In [42]:
ii64 = np.iinfo(np.int64)
print(type(ii64))

<class 'numpy.iinfo'>


In [43]:
print(ii64)

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [44]:
print(ii64.max)

9223372036854775807


In [45]:
print(type(ii64.max))

<class 'int'>


In [46]:
print(ii64.min)

-9223372036854775808


In [47]:
print(ii64.bits)

64


In [48]:
print(np.iinfo('int16'))

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------



In [49]:
print(np.iinfo('i4'))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------



In [50]:
print(np.iinfo(int))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------



In [51]:
print(np.iinfo('uint64'))

Machine parameters for uint64
---------------------------------------------------------------
min = 0
max = 18446744073709551615
---------------------------------------------------------------



In [52]:
i = 100
print(type(i))

<class 'int'>


In [53]:
print(np.iinfo(i))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------



In [54]:
ui = np.uint8(100)
print(type(ui))

<class 'numpy.uint8'>


In [55]:
print(np.iinfo(ui))

Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------



In [56]:
a = np.array([1, 2, 3], dtype=np.int8)
print(type(a))

<class 'numpy.ndarray'>


In [57]:
print(np.iinfo(a.dtype))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



In [58]:
print(np.iinfo(a[0]))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



## np.finfo()

In [59]:
fi64 = np.finfo(np.float64)
print(type(fi64))

<class 'numpy.finfo'>


In [60]:
print(fi64)

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



In [61]:
print(fi64.max)

1.7976931348623157e+308


In [62]:
print(type(fi64.max))

<class 'numpy.float64'>


In [63]:
print(fi64.min)

-1.7976931348623157e+308


In [64]:
print(fi64.eps) # exp는 엡실론

2.220446049250313e-16


In [65]:
print(fi64.bits)

64


In [66]:
print(fi64.iexp) # iexp는 지수부

11


In [67]:
print(fi64.nmant) # iexp는 가수부

52


# 문자열의 문자수에 관련한 주의사항

In [68]:
a_str = np.array([1, 2, 3], dtype=str)
print(a_str)
print(a_str.dtype)

['1' '2' '3']
<U1


In [69]:
a_str[0] = 'abcde'
print(a_str)

['a' '2' '3']


In [70]:
a_str10 = np.array([1, 2, 3], dtype='U10')
print(a_str10.dtype)

<U10


In [71]:
a_str10[0] = 'abcde'
print(a_str10)

['abcde' '2' '3']


# object형 : Python오브젝트에 대한 포인터 저장

## object형은 특수한 데이터 형으로, Python 객체에 대한 포인터를 저장

In [73]:
a_object = np.array([1, 0.1, 'one'], dtype=object)
print(a_object)

[1 0.1 'one']


In [74]:
print(a_object.dtype)

object


In [75]:
print(type(a_object[0]))
print(type(a_object[1]))
print(type(a_object[2]))

<class 'int'>
<class 'float'>
<class 'str'>


In [76]:
a_object[2] = 'oneONE'
print(a_object)

[1 0.1 'oneONE']


In [77]:
l = [1, 0.1, 'oneONE']
print(type(l[0]))
print(type(l[1]))
print(type(l[2]))

<class 'int'>
<class 'float'>
<class 'str'>


In [78]:
print(a_object * 2)

[2 0.2 'oneONEoneONE']


In [79]:
print(l * 2)

[1, 0.1, 'oneONE', 1, 0.1, 'oneONE']


# astype()을 사용한 데이터형 dtype 변환 (캐스트)

In [80]:
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(a.dtype)

[1 2 3]
int32


In [81]:
a_float = a.astype(np.float32)
print(a_float)
print(a_float.dtype)

[1. 2. 3.]
float32


In [82]:
print(a)
print(a.dtype)

[1 2 3]
int32


In [83]:
a_float = a.astype(float)
print(a_float)
print(a_float.dtype)

[1. 2. 3.]
float64


In [84]:
a_str = a.astype('str')
print(a_str)
print(a_str.dtype)

['1' '2' '3']
<U11


In [85]:
a_int = a.astype('int32')
print(a_int)
print(a_int.dtype)

[1 2 3]
int32


# astype()으로 변환(캐스트)할 때의 주의점

## float에서 int로의 캐스트 소수점 이하와 잘리고, 마이너스값은 0으로 반올림

In [86]:
a = np.arange(50).reshape((5, 10)) / 10 - 2
print(a)
print(a.dtype)

[[-2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1]
 [-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1]
 [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
 [ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]
 [ 2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9]]
float64


In [87]:
a_int = a.astype('int64')
print(a_int)
print(a_int.dtype)

[[-2 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]]
int64


### np.round()을 사용하는 경우 짝수에 대한 반올림
### (사사오입 원칙을 따른다) 반올림할 자리의 수가 5이면 반올림 할 때 앞자리의 숫자가 짝수면 내림하고 홀수면 올림

In [88]:
round(4.5)

4

In [89]:
round(3.5)

4

In [90]:
print(np.round(a).astype(int)) # -0.5가 0

[[-2 -2 -2 -2 -2 -2 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  1  1]
 [ 1  1  1  1  1  2  2  2  2  2]
 [ 2  2  2  2  2  2  3  3  3  3]]


In [91]:
def my_round(x, digit=0):
    p = 10 ** digit
    s = np.copysign(1, x)
    return (s * x * p * 2 + 1) // 2 / p * s

print(my_round(a).astype(int))  # -0.5가 -1이 되도록 하고 싶은 경우

[[-2 -2 -2 -2 -2 -2 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  0  0  0  0]
 [ 0  0  0  0  0  1  1  1  1  1]
 [ 1  1  1  1  1  2  2  2  2  2]
 [ 2  2  2  2  2  3  3  3  3  3]]


# 묵시적 형 변환

### astype()를 사용한 명시적 형변환이 아닌 연산에 따라 암묵적으로 형변환이 되는 경우o
### 예를 들어 / 연산자를 사용한 나눗셈은 부동소수점 float를 리턴

In [92]:
a = np.array([1, 2, 3])
print(a)
print(a.dtype)

[1 2 3]
int32


In [93]:
print((a / 1).dtype)

float64


In [94]:
print((a / 1.0).dtype)

float64


### +, -, *, //, **의 연산자를 사용한 연산은 정수int끼리면 int정수, float가 포함되었다면 float형

### 파이썬 산술연산자 7가지 ( + , -, *, /, **, //, %)
### 1. 덧셈 ( + ) · 2. 뺄셈 ( - ) · 3. 곱셈 ( * ) · 4. 나눗셈 ( / ) · 5. 거듭제곱 ( ** ) · 6. 몫 ( // ) 7. 나머지 ( % )

In [95]:
print((a + 1).dtype)

int32


In [96]:
print((a + 1.0).dtype)

float64


In [97]:
print((a - 1).dtype)

int32


In [98]:
print((a - 1.0).dtype)

float64


In [99]:
print((a * 1).dtype)

int32


In [100]:
print((a * 1.0).dtype)

float64


In [101]:
print((a // 1).dtype)

int32


In [102]:
print((a // 1.0).dtype)

float64


In [103]:
print((a ** 1).dtype)

int32


In [104]:
print((a ** 1.0).dtype)

float64


In [105]:
ones_int16 = np.ones(3, np.int16)
print(ones_int16)

[1 1 1]


In [106]:
ones_int32 = np.ones(3, np.int32)
print(ones_int32)

[1 1 1]


In [107]:
print((ones_int16 + ones_int32).dtype)

int32


In [108]:
ones_float16 = np.ones(3, np.float16)
print(ones_float16)

[1. 1. 1.]


In [109]:
print((ones_int16 + ones_float16).dtype)

float32
